=== JoeMob/Code/XML/XML class experiment/Experiment2.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://www.w3school.com.cn" elementFormDefault="qualified">
  <xs:element name="MemberList">
    <xs:complexType>
      <xs:attribute name="ListName" type="xs:string"/>
      <xs:sequence>
        <xs:element name="ListMaker" type="xs:string" maxOccurs="1"/>
        <xs:element name="Member" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" maxOccurs="1"/>
              <xs:element name="Age" maxOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Birthday" type="xs:date" maxOccurs="1"/>
              <xs:element name="Gender" maxOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Male"/>
                    <xs:enumeration value="Female"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="MemberCount" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="All" maxOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Male" maxOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Female" maxOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ListDate" type="xs:date" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JoeMob/Code/XML/XML class experiment/Experiment2.xml
<?xml version="1.0" encoding="utf-8"?>
<!--Edited by JoeMob-->
<?xml-stylesheet type="text/xsl" href="./Experiment2.xsl"?>
<MemberList ListName="Joe Mob's list" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Experiment2.xsd">
    <ListMaker>JoeMob</ListMaker>
    <Member>
        <Name>JoeMob</Name>
        <Age>22</Age>
        <Birthday>1998-6-26</Birthday>
        <Gender>Male</Gender>
    </Member>
    <Member>
        <Name>A</Name>
        <Age>21</Age>
        <Birthday>1999-1-1</Birthday>
        <Gender>Male</Gender>
    </Member>
    <Member>
        <Name>B</Name>
        <Age>20</Age>
        <Birthday>2000-1-1</Birthday>
        <Gender>Female</Gender>
    </Member>
    <Member>
        <Name>C</Name>
        <Age>19</Age>
        <Birthday>2001-1-1</Birthday>
        <Gender>Female</Gender>
    </Member>
    <Member>
        <Name>D</Name>
        <Age>18</Age>
        <Birthday>2002-1-1</Birthday>
        <Gender>Female</Gender>
    </Member>
    <MemberCount>
        <All>5</All>
        <Male>2</Male>
        <Female>3</Female>
    </MemberCount>
    <ListDate>2020-5-22</ListDate>
</MemberList>
